### ISSUE TITLE
io.spring.initializr  no dependency information available

### ISSUE THREAD

**Issue by naveenkumarboopathi** [BarathArivazhagan/microservice-codegen-tool#1]
Hi bro 

I got dependency issue for io.spring.initializr

Error:
  Failed to execute goal on project swagger-springboot-code-generator: Could not resolve dependencies for project com.barath.codegen:swagger-springboot-code-generator:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: io.spring.initializr:initializr-web:jar:0.6.0.RELEASE, io.spring.initializr:initializr-actuator:jar:0.6.0.RELEASE, io.spring.initializr:initializr-docs:jar:0.6.0.RELEASE: Could not find artifact io.spring.initializr:initializr-web:jar:0.6.0.RELEASE in central (https://repo.maven.apache.org/maven2)

And
[WARNING] The POM for io.spring.initializr:initializr-web:jar:0.6.0.RELEASE is missing, no dependency information available
[WARNING] The POM for io.spring.initializr:initializr-actuator:jar:0.6.0.RELEASE is missing, no dependency information available
[WARNING] The POM for io.spring.initializr:initializr-docs:jar:0.6.0.RELEASE is missing, no dependency information available

Kindly reply me to fix this bro  . i checked twice clear .m2 repo also

Thanks in advance

**Comment by BarathArivazhagan** [comment]
@naveenkumarboopathi 

Kindly clone this repository and run the builds against specific version used. 
[initializr](https://github.com/spring-io/initializr.git)

**Comment by naveenkumarboopathi** [comment]
Thanks for your support @BarathArivazhagan
